import { Doctor } from "@/types";

// Constants for filters
export const SPECIALTIES = [
  "Cardiology",
  "Dermatology",
  "Orthopedics",
  "Neurology",
  "Pediatrics",
  "Ophthalmology",
  "Gynecology",
  "Urology",
  "Dentistry",
  "Psychiatry",
  "Endocrinology",
  "Gastroenterology",
  "Pulmonology",
  "Oncology",
  "Rheumatology",
];

export const LOCATIONS = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
];

// Utility function to generate random availability
const generateAvailability = (): string[] => {
  const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const times = ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"];
  const availableDays = days.sort(() => 0.5 - Math.random()).slice(0, 4);
  return availableDays.map((day) => `${day} ${times[Math.floor(Math.random() * times.length)]}`);
};

// Generate dummy photos (using placeholder service)
const getPhotoUrl = (gender: "men" | "women", id: number) => `https://randomuser.me/api/portraits/${gender}/${id}.jpg`;

// Generate 40 dummy doctors
export const DOCTORS: Doctor[] = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    photo: getPhotoUrl("women", 1),
    specialty: "Cardiology",
    availability: generateAvailability(),
    location: "New York",
    rating: 4.8,
    experience: 12,
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    photo: getPhotoUrl("men", 2),
    specialty: "Dermatology",
    availability: generateAvailability(),
    location: "Los Angeles",
    rating: 4.7,
    experience: 8,
  },
  {
    id: 3,
    name: "Dr. Robert Williams",
    photo: getPhotoUrl("men", 3),
    specialty: "Orthopedics",
    availability: generateAvailability(),
    location: "Chicago",
    rating: 4.9,
    experience: 15,
  },
  {
    id: 4,
    name: "Dr. Emily Davis",
    photo: getPhotoUrl("women", 4),
    specialty: "Neurology",
    availability: generateAvailability(),
    location: "Houston",
    rating: 4.6,
    experience: 10,
  },
  {
    id: 5,
    name: "Dr. James Wilson",
    photo: getPhotoUrl("men", 5),
    specialty: "Pediatrics",
    availability: generateAvailability(),
    location: "Phoenix",
    rating: 4.5,
    experience: 7,
  },
  {
    id: 6,
    name: "Dr. Jennifer Brown",
    photo: getPhotoUrl("women", 6),
    specialty: "Ophthalmology",
    availability: generateAvailability(),
    location: "Philadelphia",
    rating: 4.7,
    experience: 9,
  },
  {
    id: 7,
    name: "Dr. David Martinez",
    photo: getPhotoUrl("men", 7),
    specialty: "Gynecology",
    availability: generateAvailability(),
    location: "San Antonio",
    rating: 4.8,
    experience: 11,
  },
  {
    id: 8,
    name: "Dr. Lisa Taylor",
    photo: getPhotoUrl("women", 8),
    specialty: "Urology",
    availability: generateAvailability(),
    location: "San Diego",
    rating: 4.4,
    experience: 6,
  },
  {
    id: 9,
    name: "Dr. Thomas Anderson",
    photo: getPhotoUrl("men", 9),
    specialty: "Dentistry",
    availability: generateAvailability(),
    location: "Dallas",
    rating: 4.9,
    experience: 14,
  },
  {
    id: 10,
    name: "Dr. Amanda Thompson",
    photo: getPhotoUrl("women", 10),
    specialty: "Psychiatry",
    availability: generateAvailability(),
    location: "San Jose",
    rating: 4.7,
    experience: 8,
  },
  {
    id: 11,
    name: "Dr. Christopher Garcia",
    photo: getPhotoUrl("men", 11),
    specialty: "Endocrinology",
    availability: generateAvailability(),
    location: "New York",
    rating: 4.6,
    experience: 10,
  },
  {
    id: 12,
    name: "Dr. Jessica Lee",
    photo: getPhotoUrl("women", 12),
    specialty: "Gastroenterology",
    availability: generateAvailability(),
    location: "Los Angeles",
    rating: 4.8,
    experience: 12,
  },
  {
    id: 13,
    name: "Dr. Matthew Rodriguez",
    photo: getPhotoUrl("men", 13),
    specialty: "Pulmonology",
    availability: generateAvailability(),
    location: "Chicago",
    rating: 4.5,
    experience: 7,
  },
  {
    id: 14,
    name: "Dr. Olivia Hernandez",
    photo: getPhotoUrl("women", 14),
    specialty: "Oncology",
    availability: generateAvailability(),
    location: "Houston",
    rating: 4.9,
    experience: 16,
  },
  {
    id: 15,
    name: "Dr. Daniel Martinez",
    photo: getPhotoUrl("men", 15),
    specialty: "Rheumatology",
    availability: generateAvailability(),
    location: "Phoenix",
    rating: 4.7,
    experience: 9,
  },
  {
    id: 16,
    name: "Dr. Sophia Lopez",
    photo: getPhotoUrl("women", 16),
    specialty: "Cardiology",
    availability: generateAvailability(),
    location: "Philadelphia",
    rating: 4.8,
    experience: 11,
  },
  {
    id: 17,
    name: "Dr. Andrew Gonzalez",
    photo: getPhotoUrl("men", 17),
    specialty: "Dermatology",
    availability: generateAvailability(),
    location: "San Antonio",
    rating: 4.6,
    experience: 8,
  },
  {
    id: 18,
    name: "Dr. Isabella Perez",
    photo: getPhotoUrl("women", 18),
    specialty: "Orthopedics",
    availability: generateAvailability(),
    location: "San Diego",
    rating: 4.9,
    experience: 14,
  },
  {
    id: 19,
    name: "Dr. Benjamin Torres",
    photo: getPhotoUrl("men", 19),
    specialty: "Neurology",
    availability: generateAvailability(),
    location: "Dallas",
    rating: 4.7,
    experience: 10,
  },
  {
    id: 20,
    name: "Dr. Mia Flores",
    photo: getPhotoUrl("women", 20),
    specialty: "Pediatrics",
    availability: generateAvailability(),
    location: "San Jose",
    rating: 4.5,
    experience: 6,
  },
  {
    id: 21,
    name: "Dr. William Ramirez",
    photo: getPhotoUrl("men", 21),
    specialty: "Ophthalmology",
    availability: generateAvailability(),
    location: "New York",
    rating: 4.8,
    experience: 12,
  },
  {
    id: 22,
    name: "Dr. Charlotte Reyes",
    photo: getPhotoUrl("women", 22),
    specialty: "Gynecology",
    availability: generateAvailability(),
    location: "Los Angeles",
    rating: 4.7,
    experience: 9,
  },
  {
    id: 23,
    name: "Dr. Joseph Cruz",
    photo: getPhotoUrl("men", 23),
    specialty: "Urology",
    availability: generateAvailability(),
    location: "Chicago",
    rating: 4.6,
    experience: 8,
  },
  {
    id: 24,
    name: "Dr. Amelia Ortiz",
    photo: getPhotoUrl("women", 24),
    specialty: "Dentistry",
    availability: generateAvailability(),
    location: "Houston",
    rating: 4.9,
    experience: 15,
  },
  {
    id: 25,
    name: "Dr. Samuel Morales",
    photo: getPhotoUrl("men", 25),
    specialty: "Psychiatry",
    availability: generateAvailability(),
    location: "Phoenix",
    rating: 4.5,
    experience: 7,
  },
  {
    id: 26,
    name: "Dr. Harper Gutierrez",
    photo: getPhotoUrl("women", 26),
    specialty: "Endocrinology",
    availability: generateAvailability(),
    location: "Philadelphia",
    rating: 4.7,
    experience: 10,
  },
  {
    id: 27,
    name: "Dr. Henry Vasquez",
    photo: getPhotoUrl("men", 27),
    specialty: "Gastroenterology",
    availability: generateAvailability(),
    location: "San Antonio",
    rating: 4.8,
    experience: 11,
  },
  {
    id: 28,
    name: "Dr. Evelyn Castillo",
    photo: getPhotoUrl("women", 28),
    specialty: "Pulmonology",
    availability: generateAvailability(),
    location: "San Diego",
    rating: 4.6,
    experience: 9,
  },
  {
    id: 29,
    name: "Dr. Alexander Jimenez",
    photo: getPhotoUrl("men", 29),
    specialty: "Oncology",
    availability: generateAvailability(),
    location: "Dallas",
    rating: 4.9,
    experience: 16,
  },
  {
    id: 30,
    name: "Dr. Abigail Ruiz",
    photo: getPhotoUrl("women", 30),
    specialty: "Rheumatology",
    availability: generateAvailability(),
    location: "San Jose",
    rating: 4.7,
    experience: 10,
  },
  {
    id: 31,
    name: "Dr. Jack Diaz",
    photo: getPhotoUrl("men", 31),
    specialty: "Cardiology",
    availability: generateAvailability(),
    location: "New York",
    rating: 4.8,
    experience: 12,
  },
  {
    id: 32,
    name: "Dr. Emily Mendoza",
    photo: getPhotoUrl("women", 32),
    specialty: "Dermatology",
    availability: generateAvailability(),
    location: "Los Angeles",
    rating: 4.6,
    experience: 8,
  },
  {
    id: 33,
    name: "Dr. Luke Aguilar",
    photo: getPhotoUrl("men", 33),
    specialty: "Orthopedics",
    availability: generateAvailability(),
    location: "Chicago",
    rating: 4.9,
    experience: 14,
  },
  {
    id: 34,
    name: "Dr. Scarlett Vargas",
    photo: getPhotoUrl("women", 34),
    specialty: "Neurology",
    availability: generateAvailability(),
    location: "Houston",
    rating: 4.7,
    experience: 10,
  },
  {
    id: 35,
    name: "Dr. Dylan Rios",
    photo: getPhotoUrl("men", 35),
    specialty: "Pediatrics",
    availability: generateAvailability(),
    location: "Phoenix",
    rating: 4.5,
    experience: 7,
  },
  {
    id: 36,
    name: "Dr. Zoey Romero",
    photo: getPhotoUrl("women", 36),
    specialty: "Ophthalmology",
    availability: generateAvailability(),
    location: "Philadelphia",
    rating: 4.8,
    experience: 11,
  },
  {
    id: 37,
    name: "Dr. Owen Alvarez",
    photo: getPhotoUrl("men", 37),
    specialty: "Gynecology",
    availability: generateAvailability(),
    location: "San Antonio",
    rating: 4.7,
    experience: 9,
  },
  {
    id: 38,
    name: "Dr. Lily Mendoza",
    photo: getPhotoUrl("women", 38),
    specialty: "Urology",
    availability: generateAvailability(),
    location: "San Diego",
    rating: 4.6,
    experience: 8,
  },
  {
    id: 39,
    name: "Dr. Carter Herrera",
    photo: getPhotoUrl("men", 39),
    specialty: "Dentistry",
    availability: generateAvailability(),
    location: "Dallas",
    rating: 4.9,
    experience: 15,
  },
  {
    id: 40,
    name: "Dr. Penelope Guzman",
    photo: getPhotoUrl("women", 40),
    specialty: "Psychiatry",
    availability: generateAvailability(),
    location: "San Jose",
    rating: 4.7,
    experience: 10,
  },
];
export const PAGELIMIT = 10;
